# este archivo es para correrlo desde la shell de django
# ~$ python manage.py shell < poblarBaseDeDatos.py

# Imports
from autenticacion.models import MyUser
from espacios.models import Espacio, ReservaEspacio
from articulos.models import Articulo, ReservaArticulo
from datetime import datetime, date, time, timezone, timedelta
from django.contrib.auth.hashers import make_password


#para limpiar todo menos "tom-as_12@hotmail.com" y "catapaz.vilches@gmail.com"
Articulo.objects.all().delete()
Espacio.objects.all().delete()
MyUser.objects.exclude(email="tom-as_12@hotmail.com").exclude(email="catapaz.vilches@gmail.com").delete()

# para imprimir en pantalla el estado de la población de la base de datos.
def agregado_a_DB(string):
  print(string + " agregado a la base de datos")
  return

# Definiendo los artículos y guardandolos en la base de datos.
microfono = Articulo(nombre= "micrófono1", descripcion="modelo e2019, buen estado", foto= 'articulos/microfono1.jpg')
microfono.save()
agregado_a_DB("microfono")
parlante = Articulo(nombre="parlante1", descripcion="modelo h1.23, entrada auxiliar mala", foto= 'articulos/parlante.jpg')
parlante.save()
agregado_a_DB("parlante")
equipo_musica = Articulo(nombre="equipo de musica", descripcion="equipo sony ultra mix v2, nuevo", foto= 'articulos/equipoMusica.jpeg')
equipo_musica.save()
agregado_a_DB("equipo de msica")
parrilla = Articulo(nombre="parrilla", descripcion="parrilla de asados, le falta una pata, grande", foto= 'articulos/parrilla.jpg')
parrilla.save()
agregado_a_DB("parrilla")
cable = Articulo(nombre="cable plug", descripcion="cable de 20m, para microfonos, guitarras, etc.", foto= 'articulos/cable.jpeg')
cable.save()
agregado_a_DB("cable")

# Definiendo los espacios y guardandolos en la base de datos.
sala1 = Espacio(nombre="B01", descripcion="sala de clases en el -1 de 851, para 100 alumnos, sala anfiteatro")
sala1.save()
agregado_a_DB("sala1")
salaq10 = Espacio(nombre="Q10", descripcion="sala de clases en el 1 de Quimica, para 100 alumnos, sala anfiteatro")
salaq10.save()
agregado_a_DB("salaq10")

# Definiendo unos cuantos usuarios (los usuarios admin conviene crearlos desde la consola, con el comando -> python manage.py createsuperuser)
usuario1 = MyUser( email="correo1@gmail.com", password=make_password("clave1"),nombre="Jhon Doe", rut= "1246810-12")
usuario1.save()
agregado_a_DB("usuario1")
usuario2 = MyUser(email="correo2@gmail.com", password=make_password("clave2"), nombre="Reptar Gomez", rut ="12431325-3")
usuario2.save()
agregado_a_DB("usuario2")
usuario3 = MyUser(email="correo3@gmail.com", password=make_password("clave3"), nombre="Mael Is Verdugo", rut = "446464325-8")
usuario3.is_admin=True
usuario3.save()
agregado_a_DB("usuario3 (admin)")
usuario4 = MyUser(email="correo4@gmail.com", password=make_password("clave4"), nombre="Domingo Herrera", rut = "111111-2")
usuario4.is_admin=True
usuario4.save()
agregado_a_DB("usuario4 (admin)")


#creando días y horas difererntes para crear las reservas.
tz = timezone(-timedelta(hours=-4))
d1=date(2018,5,10)
d2=date(2018,5,15)
d3=date(2018,6,1)
d4=date(2018,6,2)
d5=date(2018,6,3)
d6=date(2018,6,4)
h1=time(11,00,tzinfo=tz)
h2=time(12,00,tzinfo=tz)
h3=time(13,00,tzinfo=tz)
h4=time(14,30,tzinfo=tz)
t1=datetime.combine(d1,h1)
t12=datetime.combine(d1,h2)
t13=datetime.combine(d1,h3)
t14=datetime.combine(d1,h4)
t2=datetime.combine(d2,h1)
t22=datetime.combine(d2,h2)
t23=datetime.combine(d2,h3)
t24=datetime.combine(d2,h4)
t3=datetime.combine(d3,h1)
t32=datetime.combine(d3,h2)
t33=datetime.combine(d3,h3)
t34=datetime.combine(d3,h4)
t4=datetime.combine(d4,h1)
t42=datetime.combine(d4,h2)
t43=datetime.combine(d4,h3)
t44=datetime.combine(d4,h4)
t5=datetime.combine(d5,h1)
t52=datetime.combine(d5,h2)
t53=datetime.combine(d5,h3)
t54=datetime.combine(d5,h4)
t6=datetime.combine(d6,h1)
t62=datetime.combine(d6,h2)
t63=datetime.combine(d6,h3)
t64=datetime.combine(d6,h4)

# ahora, creando las reservas de articulos.
reserva=ReservaArticulo(usuario=usuario1, autorizador=usuario3, articulo=parlante, entrega=t1, devolucion=t2)
reserva.save()
reserva=ReservaArticulo(usuario=usuario1, autorizador=usuario3, articulo=microfono, entrega=t14, devolucion=t34)
reserva.save()
reserva=ReservaArticulo(usuario=usuario1, autorizador=usuario3, articulo=parlante, entrega=t2, devolucion=t23)
reserva.save()
reserva=ReservaArticulo(usuario=usuario1, autorizador=usuario3, articulo=cable, entrega=t4, devolucion=t44)
reserva.save()
reserva=ReservaArticulo(usuario=usuario1, autorizador=usuario3, articulo=parlante, entrega=t12, devolucion=t13)
reserva.save()
reserva=ReservaArticulo(usuario=usuario1, autorizador=usuario4, articulo=parrilla, entrega=t3, devolucion=t33)
reserva.save()
reserva=ReservaArticulo(usuario=usuario1, autorizador=usuario4, articulo=equipo_musica, entrega=t3, devolucion=t33)
reserva.save()
reserva=ReservaArticulo(usuario=usuario1, autorizador=usuario4, articulo=cable, entrega=t5, devolucion=t53)
reserva.save()
reserva=ReservaArticulo(usuario=usuario1, autorizador=usuario4, articulo=microfono, entrega=t2, devolucion=t6)
reserva.save()
reserva=ReservaArticulo(usuario=usuario1, autorizador=usuario4, articulo=parlante, entrega=t63, devolucion=t64)
reserva.save()
reserva=ReservaArticulo(usuario=usuario1, autorizador=usuario4, articulo=equipo_musica, entrega=t1, devolucion=t13)
reserva.save()
reserva=ReservaArticulo(usuario=usuario1, autorizador=usuario4, articulo=microfono, entrega=t12, devolucion=t13)
reserva.save()
agregado_a_DB("reservas de artículos del usuario1")


reserva=ReservaArticulo(usuario=usuario2, autorizador=usuario3, articulo=cable, entrega=t1, devolucion=t5)
reserva.save()
reserva=ReservaArticulo(usuario=usuario2, autorizador=usuario3, articulo=microfono, entrega=t14, devolucion=t24)
reserva.save()
reserva=ReservaArticulo(usuario=usuario2, autorizador=usuario3, articulo=parrilla, entrega=t23, devolucion=t24)
reserva.save()
reserva=ReservaArticulo(usuario=usuario2, autorizador=usuario3, articulo=cable, entrega=t24, devolucion=t4)
reserva.save()
reserva=ReservaArticulo(usuario=usuario2, autorizador=usuario3, articulo=microfono, entrega=t2, devolucion=t13)
reserva.save()
reserva=ReservaArticulo(usuario=usuario2, autorizador=usuario4, articulo=parrilla, entrega=t23, devolucion=t3)
reserva.save()
reserva=ReservaArticulo(usuario=usuario2, autorizador=usuario4, articulo=equipo_musica, entrega=t3, devolucion=t43)
reserva.save()
reserva=ReservaArticulo(usuario=usuario2, autorizador=usuario4, articulo=cable, entrega=t1, devolucion=t1)
reserva.save()
reserva=ReservaArticulo(usuario=usuario2, autorizador=usuario4, articulo=equipo_musica, entrega=t24, devolucion=t24)
reserva.save()
reserva=ReservaArticulo(usuario=usuario2, autorizador=usuario4, articulo=parrilla, entrega=t23, devolucion=t22)
reserva.save()
reserva=ReservaArticulo(usuario=usuario2, autorizador=usuario4, articulo=equipo_musica, entrega=t1, devolucion=t6)
reserva.save()
reserva=ReservaArticulo(usuario=usuario2, autorizador=usuario4, articulo=microfono, entrega=t22, devolucion=t23)
reserva.save()
agregado_a_DB("reservas de artículos del usuario2")

# ahora, creando las reservas de espacios.
reserva = ReservaEspacio(usuario=usuario1, autorizador=usuario3, espacio=sala1, inicio=t1,fin=t12)
reserva.save()
reserva = ReservaEspacio(usuario=usuario1, autorizador=usuario3, espacio=sala1, inicio=t2,fin=t32)
reserva.save()
reserva = ReservaEspacio(usuario=usuario1, autorizador=usuario4, espacio=sala1, inicio=t4,fin=t44)
reserva.save()
reserva = ReservaEspacio(usuario=usuario1, autorizador=usuario4, espacio=salaq10, inicio=t3,fin=t32)
reserva.save()
reserva = ReservaEspacio(usuario=usuario1, autorizador=usuario4, espacio=salaq10, inicio=t3,fin=t34)
reserva.save()
reserva = ReservaEspacio(usuario=usuario1, autorizador=usuario4, espacio=salaq10, inicio=t44,fin=t44)
reserva.save()
agregado_a_DB("reservas de espacios del usuario1")

reserva = ReservaEspacio(usuario=usuario2, autorizador=usuario3, espacio=sala1, inicio=t12,fin=t13)
reserva.save()
reserva = ReservaEspacio(usuario=usuario2, autorizador=usuario3, espacio=sala1, inicio=t1,fin=t32)
reserva.save()
reserva = ReservaEspacio(usuario=usuario2, autorizador=usuario4, espacio=sala1, inicio=t4,fin=t5)
reserva.save()
reserva = ReservaEspacio(usuario=usuario2, autorizador=usuario4, espacio=salaq10, inicio=t6,fin=t62)
reserva.save()
reserva = ReservaEspacio(usuario=usuario2, autorizador=usuario4, espacio=salaq10, inicio=t23,fin=t3)
reserva.save()
reserva = ReservaEspacio(usuario=usuario2, autorizador=usuario4, espacio=salaq10, inicio=t54,fin=t6)
reserva.save()
agregado_a_DB("reservas de espacios del usuario2")
print("Base de datos poblada con datos de prueba.")
