# Generated by Django 2.0.3 on 2018-07-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaespacio',
            name='estado',
            field=models.CharField(choices=[('DIS', 'Disponible'), ('PRS', 'En Prestamo'), ('REP', 'En Reparación')], default='DIS', max_length=3),
        ),
    ]
