# Generated by Django 2.0.3 on 2018-07-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0002_reservaespacio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='estado',
            field=models.CharField(choices=[('DIS', 'Disponible'), ('PRS', 'En Prestamo'), ('REP', 'En Reparación')], default='DIS', max_length=3),
        ),
        migrations.AlterField(
            model_name='reservaespacio',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('RCH', 'Aceptada'), ('RCH', 'Rechazada')], default='PEN', max_length=3),
        ),
    ]
