# Generated by Django 2.0.3 on 2018-07-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0003_auto_20180708_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaespacio',
            name='fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservaespacio',
            name='inicio',
            field=models.DateTimeField(),
        ),
    ]
