# Generated by Django 2.0.3 on 2018-07-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0004_auto_20180709_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaespacio',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('RCH', 'Aceptada'), ('RCH', 'Rechazada'), ('TER', 'Terminada')], default='PEN', max_length=3),
        ),
    ]
