# Generated by Django 2.0.3 on 2018-05-04 00:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonaNatural',
            new_name='Usuario',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='user',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
