# Generated by Django 2.0.3 on 2018-07-05 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='InventarioCEI/static/images')),
                ('estado', models.CharField(choices=[('DIS', 'Disponible'), ('PRS', 'En Prestamo'), ('REP', 'En Reparación'), ('PER', 'Perdido')], default='DIS', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega', models.DateTimeField()),
                ('devolucion', models.DateTimeField()),
                ('estado', models.CharField(choices=[('DEV', 'Devuelto'), ('NDV', 'No devuelto'), ('VIG', 'Vigente'), ('PER', 'Perdido'), ('PEN', 'Pendiente'), ('RCH', 'Rechazado'), ('ACP', 'Aceptado')], default='PEN', max_length=3)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo')),
                ('autorizador', models.ForeignKey(blank=True, limit_choices_to={'is_admin': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='map', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
