# Generated by Django 2.0.3 on 2018-07-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaarticulo',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('ACP', 'Aceptado'), ('RCH', 'Rechazado'), ('DEV', 'Devuelto'), ('NDV', 'No devuelto')], default='PEN', max_length=3),
        ),
    ]
